#ifndef ELPOSREGISTERS_GLOBAL_H
#define ELPOSREGISTERS_GLOBAL_H

#include <QtGlobal>

#if defined(ELPOSREGISTERS_LIBRARY)
#  define ELPOSREGISTERSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ELPOSREGISTERSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ELPOSREGISTERS_GLOBAL_H
